server:
  port: 3344


spring:
  application:
    name: cloud-config-center
  profiles:
    active: native #设置为本地启动的方式，而不是通过git(默认git)
  cloud:
    config:
      server:
        native:   # 可以指定本地目录
          search-locations: classpath:/config
#        git: # 也可以指定远程仓库
#          uri: git@github.com:leelovejava/springcloud-config.git
#          search-paths:
#            - spring-config
#      label: master


  rabbitmq:
    host: 47.116.65.132
    username: guest
    password: guest


eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

# 暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"