spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: gulimall-search

  redis:
    host: 192.168.56.10
    port: 6379

  session:
    store-type: redis
    timeout: 30m
server:
  port: 12000
