spring:
  cloud:
    gateway:
      routes:
        - id: baidu_route
          uri: https://www.baidu.com
          predicates:
            - Query=url, baidu  # Query指请求参数

        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url, qq

        - id: product_route
          uri: lb://gulimall-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: third_party_route
          uri: lb://gulimall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>.*),/$\{segment}

        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: search_route
          uri: lb://mall-search
          predicates:
            - Path=/api/search/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast # 路由给renren-fast，lb代表负载均衡
          predicates: # 什么情况下路由给它
            - Path=/api/** # 默认前端项目都带上api前缀，
          filters:
            - RewritePath=/api/(?<segment>.*),/renren-fast/$\{segment}  # 路由给renren-fast，并且把前缀替换为空, 请求到真实路径

        - id: gulimall_host_rout  #需要放在后面, 优先匹配api/**请求
          uri: lb://gulimall-product
          predicates:
            - Host=**.gulimall.com
