#yaml配置文件

# 测试环境
server:
  port: 8081

name: ybb

#对象
person:
  email: ybb@test.com
  name: ybb
  age: 23
  happy: false
  birth: 2020/05/05
  #map赋值
  maps: {k1:v1,k2:v2}
  lists:
    - code
    - music
    - girl
  dog:
    name: 汪汪
    age: 3


cat:
  first-name: 喵喵
  age: 3