#spring:
#  profiles:
#    active: oss, sms # 暂且先从本地配置读取, 后期从nacos中获取
#
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#
#  application:
#    name: gulimall-third-party
#
#server:
#  port: 30000
