server:
  port: 80
spring:
  application:
    name: cloud-consumer-order
  cloud:
    consul:
#      host: localhost
      host: 47.116.65.132
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        prefer-ip-address: true
        ip-address: localhost
        port: ${server.port}
        heartbeat:
          enabled: true